### ISSUE TITLE
whatrecord tests fail on tag build v0.2.0

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/whatrecord#110]
## Expected Behavior

tests should pass

## Current Behavior

- Passes at v0.1.3 but not v0.2.0
- PR builds pass, tagged build did not (does not, in the case of pcds-envs)
- Creates a massive api schema validation error that fails the test, floods the build log, and kills the job

whatrecord tests:
https://app.travis-ci.com/github/pcdshub/whatrecord/jobs/545053485
pcds-envs tests:
https://app.travis-ci.com/github/pcdshub/pcds-envs/jobs/546197478#L7106

**Comment by klauer** [comment]
Thanks for reporting it 👍 

Looks like apischema-0.16.1 became more strict about some object types, causing the deserialization failures (tuple vs list, mainly)

Short-term: could pin apischema, long-term: will have to fix the underlying types

**Comment by ZLLentz** [comment]
Ah, the classic API-breaking bugfix release!

**Comment by ZLLentz** [comment]
The full-environment travis builds are passing again after this :+1: (including the master branch build, which is rare this far after a tag)

**Comment by klauer** [comment]
That's a relief! 😥 Will worry about properly fixing this down the line.

**Comment by wyfo** [comment]
> Looks like apischema 0.16.1 0.16.0 became more strict about some object types, causing the deserialization failures (tuple vs list, mainly)

Actually, this is not the case. The changes in fact took place in the serialization, with the new  [pass through](https://wyfo.github.io/apischema/performance_and_benchmark/#serialization-passthrough) optimization. It makes notably the serialization returns the raw `tuple` serialized when its member are primitive. However, deserialization doesn't accept tuples by default (and it has never be the case for now). 

I did not thought that it could be an issue, but I did not take in account the idiom `deserialize(MyType, serialize(MyType, my_obj))` used in *whatrecord* tests. If there is tuples of primitives serialized, it's indeed expected to fail.

A "quick" fix could be to write `deserialize(MyType, json.loads(json.dumps(serialize(MyType, my_obj))))`, as it will match better the library "normal" use, but it's more code and also more test duration as json operations are very slow. So I admit it's not a good solution. Things needs to be done on *apischema* side.

**Comment by wyfo** [comment]
After *apischema* modification, there is still tests failing, but I've found that some type annotations that are wrong, what explains some *apischema* side-effects. Indeed, if a tuple is annotated with `List`, serialization will pass through it instead of convert it to `list`. 

*apischema* does have a serialization [type checking option](https://wyfo.github.io/apischema/de_serialization/#type-checking) which could spot this kind of mismatch, but in your case, there would be an issue. You are indeed mostly using the old `serialize` signature, without passing the serialized type; it's convenient, but in addition to be slower, it also has `fallback_on_any` option set by default (for compatibility reason, as it was the only behavior before), that's why even with type checking activated, it would not raise and try to serialize the mismatching type. Moreover, the type checking error message are minimal and not a lot helpful to spot the location of the error, at least for now, see https://github.com/wyfo/apischema/issues/261.

To fix type annotations, maybe abstract types like `Sequence` could be used.

**Comment by klauer** [comment]
Your input and apischema work are very much appreciated, @wyfo!

As you've noticed, there are more than a few instances of incorrect type annotations in this code base. The round-tripping of deserializing serialized data in the test suite was at least in part to help me find those problems, and also work through the idiosyncrasies of various dataclass (de)serialization libraries before I finally settled on apischema.

I'll make a point of fixing those up in the near future and see what we can do about safely moving to 0.16.3+.
